services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: webpa_db
      MYSQL_USER: webpa_user
      MYSQL_PASSWORD: webpa_password
      TZ: Europe/Brussels
    expose:
      - 3306
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    environment:
      TZ: Europe/Brussels
    expose:
      - 1025
    networks:
      - backend
    ports:
      - 8025:8025

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
      - mailpit
    environment:
      TZ: Europe/Brussels
    networks:
      - backend
    ports:
      - 8080:80

networks:
  backend:

volumes:
  mysql_data:
